# GitHub Labels Configuration for Bugbot

- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: hotfix
  color: "b60205"
  description: "Critical fix for production"

- name: perf
  color: "0e8a16"
  description: "Performance improvement"

- name: security
  color: "ee0701"
  description: "Security vulnerability or fix"

- name: chore
  color: "7057ff"
  description: "Maintenance or routine work"

- name: docs
  color: "0075ca"
  description: "Documentation changes"

- name: test
  color: "bfd4f2"
  description: "Test additions or changes"

- name: enhancement
  color: "a2eeef"
  description: "New feature or enhancement"

- name: emergency
  color: "ff0000"
  description: "Emergency communication feature"

- name: mobile
  color: "fbca04"
  description: "Mobile-specific changes"

- name: ios
  color: "1d76db"
  description: "iOS-specific changes"

- name: android
  color: "3ddc84"
  description: "Android-specific changes"

- name: offline-first
  color: "cc317c"
  description: "Offline-first features"

- name: ble-mesh
  color: "0052cc"
  description: "BLE mesh networking changes"

- name: eew
  color: "ff6b6b"
  description: "Earthquake Early Warning features"





