#!/bin/bash

echo "🔐 EAS SECRETS KURULUM SCRIPTİ"
echo ""
echo "Bu script, projede kullanılan environment variable'ları EAS Secrets olarak oluşturmanıza yardımcı olur."
echo ""
echo "📋 OLUŞTURULACAK SECRETS:"
echo "1. EXPO_PUBLIC_OPENAI_API_KEY"
echo "2. RC_IOS_KEY"
echo "3. RC_ANDROID_KEY"
echo "4. FIREBASE_API_KEY"
echo "5. FIREBASE_PROJECT_ID"
echo "6. ORG_SECRET"
echo ""
echo "⚠️  NOT: Bu script sadece komutları gösterir. Her secret için değeri manuel olarak girmeniz gerekecek."
echo ""
echo "Komutları çalıştırmak için:"
echo "  bash setup_eas_secrets.sh"
echo ""
echo "---"
echo ""

# Secrets oluşturma komutları
echo "Aşağıdaki komutları sırayla çalıştırın:"
echo ""
echo "# 1. OpenAI API Key"
echo "eas secret:create --scope project --name EXPO_PUBLIC_OPENAI_API_KEY --value YOUR_VALUE"
echo ""
echo "# 2. RevenueCat iOS Key"
echo "eas secret:create --scope project --name RC_IOS_KEY --value YOUR_VALUE"
echo ""
echo "# 3. RevenueCat Android Key"
echo "eas secret:create --scope project --name RC_ANDROID_KEY --value YOUR_VALUE"
echo ""
echo "# 4. Firebase API Key"
echo "eas secret:create --scope project --name FIREBASE_API_KEY --value YOUR_VALUE"
echo ""
echo "# 5. Firebase Project ID"
echo "eas secret:create --scope project --name FIREBASE_PROJECT_ID --value YOUR_VALUE"
echo ""
echo "# 6. Backend Secret"
echo "eas secret:create --scope project --name ORG_SECRET --value YOUR_VALUE"
echo ""
echo "---"
echo ""
echo "✅ Secrets oluşturulduktan sonra:"
echo "  eas build --platform ios --profile production"
