/**
 * DISASTER MAP SCREEN - Styles
 * Extracted from DisasterMapScreen.tsx for maintainability
 */

import { StyleSheet } from 'react-native';

export const PREMIUM_COLORS = {
  trustBlue: '#1F4E79',
  trustBlueDark: '#163B5B',
  trustBlueLight: '#4A769E',
  cream: '#F4EFE7',
  ivory: '#FFFCF7',
  textPrimary: '#121416',
  textSecondary: '#5B5F66',
  safe: '#2E7D32',
  warning: '#D9A441',
  critical: '#B53A3A',
  criticalDark: '#962A2A',
  glass: 'rgba(255, 252, 247, 0.92)',
  glassBorder: 'rgba(31, 78, 121, 0.12)',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PREMIUM_COLORS.cream,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: PREMIUM_COLORS.cream,
  },
  loadingIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 16,
  },
  loadingText: {
    fontSize: 16,
    color: PREMIUM_COLORS.textSecondary,
    textAlign: 'center',
  },

  // PREMIUM: Header
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    paddingHorizontal: 16,
  },
  headerBlur: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  headerGradient: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  headerBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(31, 78, 121, 0.08)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 4,
  },
  viewModeToggle: {
    flexDirection: 'row',
    backgroundColor: 'rgba(31,78,121,0.08)',
    borderRadius: 12,
    padding: 3,
  },
  viewModeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    gap: 6,
  },
  viewModeBtnActive: {
    backgroundColor: PREMIUM_COLORS.trustBlue,
  },
  viewModeBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: PREMIUM_COLORS.textSecondary,
  },
  viewModeBtnTextActive: {
    color: '#fff',
  },

  // EEW Badge
  eewBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: PREMIUM_COLORS.safe + '15',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.safe + '30',
  },
  eewPulse: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: PREMIUM_COLORS.safe + '10',
    borderRadius: 12,
  },
  eewBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: PREMIUM_COLORS.safe,
  },

  // PREMIUM: Floating Controls
  floatingControls: {
    position: 'absolute',
    right: 16,
    gap: 12,
    alignItems: 'center',
  },
  controlBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: PREMIUM_COLORS.glass,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  controlBtnPrimary: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  controlBtnInner: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomControls: {
    backgroundColor: PREMIUM_COLORS.glass,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  zoomBtn: {
    width: 50,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomDivider: {
    height: 1,
    backgroundColor: PREMIUM_COLORS.glassBorder,
  },

  // Pulse Marker
  pulseContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  pulseRing: {
    position: 'absolute',
    borderWidth: 2,
    backgroundColor: 'transparent',
  },
  pulseCenter: {
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },

  // PREMIUM: Family Marker
  familyMarkerContainer: {
    alignItems: 'center',
  },
  familyMarkerOuter: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  familyMarkerInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: PREMIUM_COLORS.glass,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  familyMarkerInitial: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PREMIUM_COLORS.textPrimary,
  },
  statusDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2.5,
  },
  batteryBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  nameLabel: {
    marginTop: 6,
    backgroundColor: PREMIUM_COLORS.glass,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    maxWidth: 90,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  nameLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: PREMIUM_COLORS.textPrimary,
    textAlign: 'center',
  },

  // PREMIUM: Bottom Sheet
  bottomSheetBg: {
    backgroundColor: PREMIUM_COLORS.ivory,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  bottomSheetHandle: {
    backgroundColor: PREMIUM_COLORS.trustBlue + '40',
    width: 40,
    height: 5,
    borderRadius: 3,
  },
  sheetContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  sheetTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: PREMIUM_COLORS.textPrimary,
    marginBottom: 20,
    marginTop: 8,
  },

  // Empty State
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyStateIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: PREMIUM_COLORS.trustBlue + '10',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: PREMIUM_COLORS.textPrimary,
    marginTop: 8,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: PREMIUM_COLORS.textSecondary,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 20,
  },

  // PREMIUM: Member Card
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: PREMIUM_COLORS.glassBorder,
  },
  memberAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberAvatarText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  memberInfo: {
    flex: 1,
    marginLeft: 14,
  },
  memberName: {
    fontSize: 17,
    fontWeight: '600',
    color: PREMIUM_COLORS.textPrimary,
  },
  memberMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    gap: 10,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 5,
  },
  statusDotSmall: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  lastSeenText: {
    fontSize: 12,
    color: PREMIUM_COLORS.textSecondary,
  },

  // Detail View
  detailView: {
    paddingTop: 8,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  backBtnText: {
    fontSize: 17,
    color: PREMIUM_COLORS.trustBlue,
    fontWeight: '500',
  },
  memberDetail: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  memberDetailAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  memberDetailAvatarText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
  },
  memberDetailName: {
    fontSize: 26,
    fontWeight: 'bold',
    color: PREMIUM_COLORS.textPrimary,
    marginBottom: 12,
  },
  statusBadgeLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 14,
    gap: 8,
  },
  statusDotLarge: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusBadgeLargeText: {
    fontSize: 15,
    fontWeight: '600',
  },

  // PREMIUM: Info Cards
  infoCards: {
    marginTop: 24,
    gap: 12,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PREMIUM_COLORS.cream,
    padding: 16,
    borderRadius: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  infoCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: PREMIUM_COLORS.trustBlue + '10',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoCardLabel: {
    fontSize: 13,
    color: PREMIUM_COLORS.textSecondary,
    marginBottom: 2,
  },
  infoCardValue: {
    fontSize: 16,
    fontWeight: '600',
    color: PREMIUM_COLORS.textPrimary,
  },

  // PREMIUM: Action Buttons
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 28,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: PREMIUM_COLORS.cream,
    gap: 8,
    borderWidth: 1,
    borderColor: PREMIUM_COLORS.glassBorder,
  },
  actionBtnPrimary: {
    flex: 2,
    borderRadius: 16,
    shadowColor: PREMIUM_COLORS.trustBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  actionBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  actionBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: PREMIUM_COLORS.trustBlue,
  },
  actionBtnPrimaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },

  // Earthquake
  quakeInfo: {
    marginTop: 8,
  },
  quakeInfoGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    gap: 14,
  },
  quakeInfoText: {
    fontSize: 16,
    color: PREMIUM_COLORS.textPrimary,
    fontWeight: '500',
    flex: 1,
  },
  quakeDetail: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  magnitudeCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  magnitudeText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  quakeLocation: {
    fontSize: 20,
    fontWeight: '600',
    color: PREMIUM_COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  quakeTime: {
    fontSize: 15,
    color: PREMIUM_COLORS.textSecondary,
  },

  // PREMIUM: SOS Signal Markers
  sosMarkerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosMarkerPulse: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#dc2626',
  },
  sosMarkerMain: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#dc2626',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  sosMarkerLabel: {
    backgroundColor: 'rgba(220, 38, 38, 0.95)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 6,
    alignItems: 'center',
    minWidth: 80,
  },
  sosMarkerName: {
    fontSize: 10,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 0.5,
  },
  sosMarkerInfo: {
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
  },
});
