/**
 * CINEMATIC ONBOARDING SCREEN
 * "The Veo Experience"
 * 
 * Plays a high-fidelity cinematic intro (generated by Gemini Veo) 
 * to welcome users with a "Netflix-style" premium feel.
 * 
 * - Sound Design: Deep bass hum + crystal clear voiceover.
 * - Haptics: Synced with video impact points.
 * - Visuals: Full screen, immersive, no status bar.
 */

import React, { useRef, useState, useEffect } from 'react';
import { View, StyleSheet, Text, TouchableOpacity, Animated, useWindowDimensions, StatusBar } from 'react-native';
import { Video, ResizeMode, AVPlaybackStatus } from 'expo-av';
import * as Haptics from 'expo-haptics';
import { LinearGradient } from 'expo-linear-gradient';
import { useNavigation } from '@react-navigation/native';
import { useOnboardingStore } from '../stores/onboardingStore';

// "Cyber Earth" Network Theme - High Quality Loop
const CINEMATIC_VIDEO_URI = 'https://videos.pexels.com/video-files/3129671/3129671-uhd_2560_1440_30fps.mp4';
// Backup: 'https://videos.pexels.com/video-files/855564/855564-hd_1920_1080_30fps.mp4' (Digital Network)

export const CinematicOnboardingScreen = () => {
  const { width, height } = useWindowDimensions();
  const videoRef = useRef<Video>(null);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const [status, setStatus] = useState<AVPlaybackStatus | {}>({});
  const navigation = useNavigation<any>();

  useEffect(() => {
    // Start fade in
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 1000,
      useNativeDriver: true,
    }).start();

    // Initial Haptic Impact
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
  }, []);

  const handleComplete = () => {
    // Dramatic Haptic Exit
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);

    // Complete Onboarding - CoreApp will switch to MainNavigator
    useOnboardingStore.getState().setCompleted(true);
  };

  const onPlaybackStatusUpdate = (status: AVPlaybackStatus) => {
    setStatus(status);
    if (status.isLoaded && status.didJustFinish) {
      handleComplete();
    }
  };

  return (
    <View style={styles.container}>
      <StatusBar hidden />

      <Video
        ref={videoRef}
        style={[styles.video, { width, height }]}
        source={{ uri: CINEMATIC_VIDEO_URI }}
        resizeMode={ResizeMode.COVER}
        isLooping={false}
        shouldPlay
        onPlaybackStatusUpdate={onPlaybackStatusUpdate}
      />

      <Animated.View style={[styles.overlay, { opacity: fadeAnim }]}>
        <LinearGradient
          colors={['transparent', 'rgba(0,0,0,0.8)']}
          style={[styles.gradient, { height: height * 0.5 }]}
        >
          <View style={styles.content}>
            <Text style={styles.eliteTitle}>AFETNET</Text>
            <Text style={styles.eliteSubtitle}>WHEN THE WORLD GOES DARK, WE GUIDE YOU HOME.</Text>

            <TouchableOpacity
              style={styles.button}
              onPress={handleComplete}
            >
              <Text style={styles.buttonText}>ENTER THE NETWORK</Text>
            </TouchableOpacity>
          </View>
        </LinearGradient>
      </Animated.View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  video: {
    position: 'absolute',
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  gradient: {
    justifyContent: 'flex-end',
    paddingBottom: 50,
    paddingHorizontal: 20,
  },
  content: {
    alignItems: 'center',
  },
  eliteTitle: {
    color: '#fff',
    fontSize: 42,
    fontWeight: '800',
    letterSpacing: 4,
    marginBottom: 8,
    textShadowColor: 'rgba(0, 255, 150, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
    fontFamily: 'System', // Use custom font if available
  },
  eliteSubtitle: {
    color: '#ccc',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 2,
    marginBottom: 40,
    textAlign: 'center',
  },
  button: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    // backdropFilter: 'blur(10px)', // Removed: Web only support
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 2,
  },
});
