services:
  # Backend API
  - type: web
    name: afetnet-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install && npx tsc --skipLibCheck && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: afetnet-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: afetnet-redis
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://afetnet.app,https://www.afetnet.app
      - key: AFAD_API_URL
        value: https://deprem.afad.gov.tr/EventData/GetLast100Event
      - key: USGS_API_URL
        value: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson
      - key: LOG_LEVEL
        value: info

databases:
  - name: afetnet-db
    databaseName: afetnet
    user: afetnet
    region: frankfurt
    plan: free
    ipAllowList: []

# Redis (optional - for caching)
# Note: Redis requires paid plan on Render
# - type: redis
#   name: afetnet-redis
#   region: frankfurt
#   plan: starter
#   maxmemoryPolicy: allkeys-lru


