import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'help_requests',
      columns: [
        { name: 'timestamp', type: 'number' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'accuracy', type: 'number' },
        { name: 'priority', type: 'string' },
        { name: 'under_rubble', type: 'boolean' },
        { name: 'injured', type: 'boolean' },
        { name: 'people_count', type: 'number' },
        { name: 'battery', type: 'number' },
        { name: 'anonymity', type: 'boolean' },
        { name: 'ttl', type: 'number' },
        { name: 'delivered', type: 'boolean' },
        { name: 'hops', type: 'number' },
        { name: 'source', type: 'string' },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'status_pings',
      columns: [
        { name: 'timestamp', type: 'number' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'accuracy', type: 'number' },
        { name: 'battery', type: 'number' },
        { name: 'anonymity', type: 'boolean' },
        { name: 'ttl', type: 'number' },
        { name: 'delivered', type: 'boolean' },
        { name: 'hops', type: 'number' },
        { name: 'source', type: 'string' },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'resource_posts',
      columns: [
        { name: 'timestamp', type: 'number' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'accuracy', type: 'number' },
        { name: 'type', type: 'string' },
        { name: 'qty', type: 'string' },
        { name: 'desc', type: 'string', isOptional: true },
        { name: 'ttl', type: 'number' },
        { name: 'delivered', type: 'boolean' },
        { name: 'hops', type: 'number' },
        { name: 'source', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'damage_reports',
      columns: [
        { name: 'timestamp', type: 'number' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'accuracy', type: 'number' },
        { name: 'type', type: 'string' },
        { name: 'severity', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'photo_path', type: 'string', isOptional: true },
        { name: 'reporter_name', type: 'string', isOptional: true },
        { name: 'reporter_phone', type: 'string', isOptional: true },
        { name: 'confirmed', type: 'boolean' },
        { name: 'delivered', type: 'boolean' },
        { name: 'source', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'shelters',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'capacity', type: 'number' },
        { name: 'current_occupancy', type: 'number' },
        { name: 'amenities', type: 'string', isOptional: true },
        { name: 'contact_info', type: 'string', isOptional: true },
        { name: 'verified', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'device_peers',
      columns: [
        { name: 'device_id', type: 'string' },
        { name: 'last_seen', type: 'number' },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'rssi', type: 'number', isOptional: true },
        { name: 'connection_type', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});

export const migrations = [
  // Add migrations here when needed
];