/**
 * HEALTH PROFILE SCREEN - Styles
 * Extracted from HealthProfileScreen.tsx for maintainability
 */

import { StyleSheet } from 'react-native';
import { colors, typography, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F1EB', // Cream background
  },
  // Summary Card Styles
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: spacing[4],
    marginBottom: spacing[5],
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.08)',
    shadowColor: '#1E3A5F',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[3],
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1E3A5F',
    letterSpacing: 0.2,
  },
  summaryGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#8FA8BE',
    fontWeight: '500',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E3A5F',
  },
  summaryDivider: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(30, 58, 95, 0.1)',
  },
  bmiIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    marginTop: spacing[3],
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[3],
    borderRadius: 10,
    borderWidth: 1,
  },
  bmiText: {
    fontSize: 13,
    fontWeight: '600',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: spacing[3],
    zIndex: 100,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    overflow: 'hidden',
  },
  backButtonInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(30, 58, 95, 0.08)',
    borderRadius: 14,
  },
  backButtonGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  headerTitle: {
    ...typography.h2,
    color: '#1E3A5F', // Navy
    fontWeight: '700',
    fontSize: 22,
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    ...typography.caption,
    color: '#5A7894', // Muted navy
    fontSize: 13,
    fontWeight: '500',
  },
  headerRight: {
    width: 44,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: spacing[3],
  },
  categoryContainer: {
    marginBottom: spacing[6],
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginBottom: spacing[4],
    paddingHorizontal: spacing[2],
  },
  categoryIconGradient: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1E3A5F',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  categoryTitle: {
    ...typography.h3,
    color: '#1E3A5F', // Navy
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 0.2,
    flex: 1,
  },
  addContactButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    overflow: 'hidden',
  },
  addContactButtonGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryContent: {
    backgroundColor: '#FFFFFF', // White card
    borderRadius: 20,
    padding: spacing[4],
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.08)',
    shadowColor: '#1E3A5F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    marginHorizontal: 0,
  },
  formRow: {
    marginBottom: spacing[4],
  },
  label: {
    ...typography.body,
    color: '#1E3A5F', // Navy
    marginBottom: spacing[2],
    fontWeight: '600',
    fontSize: 15,
    letterSpacing: 0.1,
  },
  input: {
    backgroundColor: '#F8F6F2', // Light cream
    borderRadius: 14,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3] + 2,
    color: '#1E3A5F', // Navy text
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.1)',
    minHeight: 52,
    marginHorizontal: 0,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
    paddingTop: spacing[3],
  },
  row: {
    flexDirection: 'row',
    gap: spacing[3],
  },
  halfInput: {
    flex: 1,
  },
  buttonGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    paddingHorizontal: 0,
  },
  button: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    borderRadius: 12,
    backgroundColor: '#F8F6F2',
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.1)',
    minHeight: 46,
    overflow: 'hidden',
  },
  buttonActive: {
    borderColor: '#5A9F68',
  },
  buttonText: {
    ...typography.body,
    color: '#5A7894',
    fontWeight: '600',
    fontSize: 14,
    zIndex: 1,
  },
  buttonTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  bloodTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    paddingHorizontal: 0,
  },
  bloodTypeButton: {
    width: '11.8%',
    minWidth: 70,
    maxWidth: 80,
    height: 56,
    borderRadius: 14,
    backgroundColor: '#F8F6F2',
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bloodTypeButtonActive: {
    borderColor: '#B53A3A',
  },
  bloodTypeText: {
    ...typography.body,
    fontWeight: '700',
    fontSize: 17,
    color: '#5A7894',
    zIndex: 1,
  },
  bloodTypeTextActive: {
    color: '#ffffff',
    fontSize: 18,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginBottom: spacing[2],
    paddingHorizontal: 0,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(90, 159, 104, 0.12)',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(90, 159, 104, 0.25)',
    gap: spacing[1],
    minHeight: 38,
  },
  chipText: {
    ...typography.body,
    color: '#1E3A5F',
    fontSize: 14,
    fontWeight: '600',
  },
  chipRemove: {
    padding: 2,
  },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingHorizontal: 0,
  },
  addInput: {
    flex: 1,
    backgroundColor: '#F8F6F2',
    borderRadius: 14,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    color: '#1E3A5F',
    fontSize: 15,
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.1)',
    minHeight: 50,
    marginHorizontal: 0,
  },
  addButton: {
    width: 50,
    height: 50,
    borderRadius: 14,
    overflow: 'hidden',
  },
  addButtonGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: spacing[4],
    marginBottom: spacing[3],
    marginHorizontal: 0,
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.08)',
  },
  contactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[4],
  },
  contactHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  contactIconGradient: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactTitle: {
    ...typography.h4,
    color: '#1E3A5F',
    fontWeight: '700',
    fontSize: 16,
  },
  removeButton: {
    padding: spacing[1],
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[6] * 2,
  },
  emptyStateText: {
    ...typography.h4,
    color: '#5A7894',
    textAlign: 'center',
    marginTop: spacing[3],
    fontWeight: '600',
    fontSize: 16,
  },
  emptyStateSubtext: {
    ...typography.body,
    color: '#8FA8BE',
    textAlign: 'center',
    marginTop: spacing[2],
    fontSize: 13,
  },
  saveContainer: {
    marginTop: spacing[6],
    marginBottom: spacing[4],
  },
  saveButton: {
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#5A9F68',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  saveButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[5],
    gap: spacing[3],
  },
  saveButtonText: {
    ...typography.button,
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  // First Aid Styles
  firstAidCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFAFA',
    borderRadius: 14,
    padding: spacing[4],
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.06)',
  },
  firstAidIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
  },
  firstAidInfo: {
    flex: 1,
  },
  firstAidTitle: {
    ...typography.body,
    color: '#1E3A5F',
    fontWeight: '700',
    fontSize: 15,
    marginBottom: 3,
  },
  firstAidDesc: {
    ...typography.caption,
    color: '#5A7894',
    fontSize: 12,
  },
  // Emergency Card Styles
  emergencyCardPreview: {
    backgroundColor: 'rgba(181, 58, 58, 0.06)',
    borderRadius: 18,
    padding: spacing[5],
    borderWidth: 2,
    borderColor: 'rgba(181, 58, 58, 0.2)',
    marginBottom: spacing[4],
  },
  emergencyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(181, 58, 58, 0.15)',
    paddingBottom: spacing[3],
  },
  emergencyCardTitle: {
    ...typography.h3,
    color: '#B53A3A',
    fontWeight: '800',
    fontSize: 17,
    letterSpacing: 0.8,
  },
  emergencyCardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(181, 58, 58, 0.08)',
  },
  emergencyCardLabel: {
    ...typography.body,
    color: '#5A7894',
    fontWeight: '600',
    fontSize: 13,
    flex: 0.4,
  },
  emergencyCardValue: {
    ...typography.body,
    color: '#1E3A5F',
    fontWeight: '700',
    fontSize: 13,
    flex: 0.6,
    textAlign: 'right',
  },
  shareButtonsRow: {
    flexDirection: 'row',
    gap: spacing[3],
    marginBottom: spacing[3],
  },
  shareButton: {
    flex: 1,
    borderRadius: 14,
    overflow: 'hidden',
  },
  shareButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[3],
    gap: spacing[2],
  },
  shareButtonText: {
    ...typography.button,
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  emergencyCardHint: {
    ...typography.caption,
    color: '#8FA8BE',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: spacing[2],
  },
});
