/**
 * NEWS DETAIL SCREEN STYLES
 * Extracted from NewsDetailScreen for clean code architecture
 * All styles are centralized here for maintainability
 */

import { StyleSheet } from 'react-native';
import { colors, typography } from '../../../theme';

// ELITE: Premium cream background color constant
export const CREAM_BACKGROUND = '#FDFBF7';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: CREAM_BACKGROUND,
        paddingTop: 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 0,
        paddingBottom: 8,
        backgroundColor: CREAM_BACKGROUND,
        borderBottomWidth: 0,
        minHeight: 44,
    },
    backButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        marginHorizontal: 8,
    },
    headerTitle: {
        ...typography.h3,
        color: colors.text.primary,
    },
    headerSubtitle: {
        ...typography.caption,
        color: colors.text.secondary,
        marginTop: 0,
    },
    shareButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    backButtonCircle: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: 'rgba(15, 23, 42, 0.05)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    shareButtonCircle: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: 'rgba(15, 23, 42, 0.05)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    titleContainer: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 16,
        backgroundColor: CREAM_BACKGROUND,
        borderBottomWidth: 0,
    },
    title: {
        fontSize: 22,
        fontWeight: '700',
        color: '#0F172A',
        marginBottom: 8,
        lineHeight: 28,
        letterSpacing: -0.3,
    },
    meta: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    metaText: {
        ...typography.caption,
        color: colors.text.secondary,
    },
    metaDot: {
        ...typography.caption,
        color: colors.text.tertiary,
        marginHorizontal: 8,
    },
    magnitudeBadge: {
        backgroundColor: colors.emergency.critical,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    magnitudeText: {
        ...typography.small,
        fontWeight: '700',
        color: '#fff',
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: CREAM_BACKGROUND,
        paddingHorizontal: 20,
        paddingBottom: 12,
        gap: 12,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: 'rgba(148, 163, 184, 0.1)',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    tabActive: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderColor: 'rgba(59, 130, 246, 0.3)',
    },
    tabText: {
        fontSize: 14,
        color: '#64748B',
        fontWeight: '600',
    },
    tabTextActive: {
        color: '#3B82F6',
        fontWeight: '700',
    },
    content: {
        flex: 1,
    },
    contentPadding: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 32,
    },
    fallbackScroll: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    loadingText: {
        ...typography.body,
        color: colors.text.secondary,
        marginTop: 16,
    },
    summaryCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 20,
        padding: 24,
        borderWidth: 0,
        marginBottom: 20,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 4,
    },
    summaryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 16,
    },
    summaryTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0F172A',
    },
    summaryText: {
        fontSize: 16,
        fontWeight: '400',
        color: '#334155',
        lineHeight: 26,
        letterSpacing: 0.1,
    },
    emptySummaryContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        padding: 16,
        backgroundColor: 'rgba(148, 163, 184, 0.1)',
        borderRadius: 12,
    },
    emptySummaryText: {
        flex: 1,
        ...typography.body,
        color: colors.text.secondary,
        lineHeight: 20,
    },
    disclaimer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        padding: 16,
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.2)',
        marginBottom: 20,
    },
    disclaimerText: {
        flex: 1,
        ...typography.small,
        color: colors.text.secondary,
        lineHeight: 18,
    },
    originalButton: {
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 20,
    },
    originalButtonInline: {
        marginBottom: 0,
    },
    originalButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 16,
    },
    originalButtonText: {
        ...typography.button,
        color: '#fff',
    },
    browserModal: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    browserHeader: {
        paddingHorizontal: 16,
        paddingBottom: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    browserCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(148, 163, 184, 0.24)',
        backgroundColor: 'rgba(15, 23, 42, 0.35)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    browserHeaderCenter: {
        flex: 1,
        marginHorizontal: 4,
    },
    browserHeaderTitle: {
        ...typography.caption,
        color: colors.text.secondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    browserHeaderSubtitle: {
        ...typography.body,
        color: colors.text.primary,
        marginTop: 4,
    },
    browserHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    browserActionButton: {
        width: 40,
        height: 40,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(148, 163, 184, 0.24)',
        backgroundColor: 'rgba(15, 23, 42, 0.35)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    browserWebView: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    browserLoading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 48,
        gap: 16,
    },
    browserLoadingText: {
        ...typography.body,
        color: colors.text.secondary,
    },
    htmlFallbackContainer: {
        width: '100%',
        backgroundColor: colors.background.primary,
        paddingBottom: 100,
        minHeight: 400,
    },
    htmlFallbackContainerFullScreen: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 5,
        paddingTop: 0,
        marginTop: 0,
        backgroundColor: colors.background.primary,
    },
    browserHtmlScroll: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    browserHtmlContent: {
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 100,
        gap: 16,
    },
    browserHtmlContentFullScreen: {
        paddingTop: 60,
    },
    fullScreenBottomButton: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: 25,
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 0,
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
    },
    fullScreenBottomButtonInner: {
        borderRadius: 12,
        overflow: 'hidden',
    },
    fullScreenBottomButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 16,
    },
    fullScreenBottomButtonText: {
        ...typography.button,
        color: '#fff',
    },
    browserHtmlText: {
        ...typography.body,
        color: colors.text.primary,
        lineHeight: 24,
    },
    htmlContentWrapper: {
        width: '100%',
        minHeight: 200,
        backgroundColor: colors.background.primary,
        paddingVertical: 16,
        paddingHorizontal: 4,
    },
    originalContainer: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    originalContainerFullScreen: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 10,
        paddingTop: 0,
        backgroundColor: colors.background.primary,
    },
    fullScreenFloatingHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 30,
        backgroundColor: 'transparent',
    },
    fullScreenFloatingHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    fullScreenFloatingBackButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fullScreenFloatingActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    fullScreenFloatingActionButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fullScreenHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
        paddingHorizontal: 16,
        paddingBottom: 12,
    },
    fullScreenHeaderGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(148, 163, 184, 0.2)',
    },
    fullScreenBackButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 20,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
    },
    fullScreenHeaderCenter: {
        flex: 1,
        marginHorizontal: 12,
        alignItems: 'center',
    },
    fullScreenHeaderTitle: {
        ...typography.body,
        color: colors.text.primary,
        fontWeight: '600',
    },
    fullScreenHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    fullScreenActionButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    originalActions: {
        paddingHorizontal: 20,
        paddingBottom: 24,
        backgroundColor: colors.background.primary,
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
    },
    webViewContainer: {
        flex: 1,
        backgroundColor: colors.background.primary,
        paddingBottom: 80,
    },
    webViewWrapper: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    webViewWrapperFullScreen: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 5,
        paddingTop: 0,
        marginTop: 0,
        backgroundColor: colors.background.primary,
    },
    webView: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    webViewFullScreen: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    webViewButtonContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 20,
        paddingBottom: 20,
        paddingTop: 12,
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        borderTopWidth: 1,
        borderTopColor: colors.border.light,
        zIndex: 10,
    },
    webViewLoading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 60,
        backgroundColor: colors.background.primary,
    },
    articleCard: {
        backgroundColor: colors.background.card,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: colors.border.light,
        marginBottom: 20,
    },
    articleHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 16,
    },
    articleTitle: {
        ...typography.h4,
        color: colors.text.primary,
        fontWeight: '700',
    },
    articleText: {
        ...typography.body,
        color: colors.text.primary,
        lineHeight: 24,
    },
    inlineNotice: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        padding: 16,
        backgroundColor: 'rgba(59, 130, 246, 0.08)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.24)',
        marginBottom: 20,
    },
    inlineNoticeText: {
        flex: 1,
        ...typography.small,
        color: colors.text.secondary,
        lineHeight: 18,
    },
    errorBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        padding: 16,
        backgroundColor: 'rgba(248, 113, 113, 0.08)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(248, 113, 113, 0.4)',
    },
    errorText: {
        flex: 1,
        ...typography.body,
        color: colors.text.secondary,
        lineHeight: 20,
    },
    noUrlContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    noUrlText: {
        marginTop: 16,
        textAlign: 'center',
        ...typography.body,
        color: colors.text.secondary,
    },
    safariInfoContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 32,
        marginBottom: 24,
        backgroundColor: colors.background.card,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.border.light,
    },
    safariInfoTitle: {
        marginTop: 16,
        marginBottom: 12,
        textAlign: 'center',
        ...typography.h4,
        color: colors.text.primary,
        fontWeight: '700',
    },
    safariInfoText: {
        textAlign: 'center',
        ...typography.body,
        color: colors.text.secondary,
        lineHeight: 22,
        marginBottom: 20,
    },
    originalPromptContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 48,
    },
    originalPromptTitle: {
        ...typography.h3,
        color: colors.text.primary,
        marginTop: 24,
        marginBottom: 12,
        fontWeight: '700',
    },
    originalPromptText: {
        ...typography.body,
        color: colors.text.secondary,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 32,
    },
    retryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 16,
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: 'rgba(59, 130, 246, 0.15)',
        borderRadius: 8,
        alignSelf: 'center',
    },
    retryButtonText: {
        ...typography.body,
        color: colors.accent.primary,
        fontWeight: '600',
    },
    emptyContentContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 48,
        paddingHorizontal: 24,
        minHeight: 300,
    },
    emptyContentText: {
        ...typography.body,
        color: colors.text.secondary,
        marginTop: 16,
        textAlign: 'center',
    },
    // In-App Browser Styles
    inAppBrowserContainer: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    inAppBrowserHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingBottom: 0,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
        backgroundColor: colors.background.primary,
        minHeight: 32,
    },
    inAppBrowserBackButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 16,
        backgroundColor: colors.background.secondary,
    },
    inAppBrowserHeaderCenter: {
        flex: 1,
        marginHorizontal: 8,
        alignItems: 'center',
    },
    inAppBrowserHeaderTitle: {
        ...typography.caption,
        color: colors.text.primary,
        fontWeight: '600',
        fontSize: 12,
    },
    inAppBrowserHeaderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    inAppBrowserActionButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 16,
        backgroundColor: colors.background.secondary,
    },
    inAppBrowserWebView: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    inAppBrowserLoading: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background.primary,
        gap: 16,
    },
    inAppBrowserLoadingText: {
        ...typography.body,
        color: colors.text.secondary,
        marginTop: 12,
    },
    // Inline WebView styles
    inlineWebViewContainer: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    inlineWebViewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: colors.background.secondary,
        borderBottomWidth: 1,
        borderBottomColor: colors.border.light,
    },
    inlineWebViewTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    inlineWebViewTitle: {
        ...typography.h4,
        color: colors.text.primary,
        fontWeight: '700',
    },
    inlineWebViewExternalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: colors.accent.primary + '15',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: colors.accent.primary + '30',
    },
    inlineWebViewExternalText: {
        ...typography.caption,
        color: colors.accent.primary,
        fontWeight: '600',
    },
    inlineWebView: {
        flex: 1,
        backgroundColor: colors.background.primary,
    },
    inlineWebViewLoading: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background.primary,
        gap: 12,
        padding: 24,
    },
    inlineWebViewLoadingText: {
        ...typography.body,
        color: colors.text.secondary,
        textAlign: 'center',
    },
    inlineWebViewFallback: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background.primary,
        gap: 16,
        padding: 24,
    },
    inlineWebViewFallbackText: {
        ...typography.body,
        color: colors.text.secondary,
        textAlign: 'center',
    },
});

export default styles;
