/**
 * WAVE VISUALIZATION SCREEN - Extracted Styles
 */
import { StyleSheet, Dimensions } from 'react-native';
import { colors as colorsImport } from '../../theme';

const colors = colorsImport || {
  background: { primary: '#0a0e1a', secondary: '#0f1419', elevated: '#1a1f2e', card: '#141824', overlay: 'rgba(10, 14, 26, 0.95)', input: '#1a1f2e', tertiary: '#1a1f2e' },
  text: { primary: '#ffffff', secondary: '#a0aec0', tertiary: '#718096', disabled: '#4a5568', muted: '#718096' },
  accent: { primary: '#3b82f6', secondary: '#60a5fa', glow: 'rgba(59, 130, 246, 0.15)' },
};

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.text.secondary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
  },
  errorText: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: '700',
    color: colors.text.primary,
  },
  errorSubtext: {
    marginTop: 8,
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: ((colors as any).accent?.primary) || ((colors as any).primary?.main) || '#3b82f6',
    borderRadius: 12,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    minHeight: SCREEN_HEIGHT - 200,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: '700',
    color: colors.text.primary,
  },
  emptySubtext: {
    marginTop: 8,
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  safeArea: {
    flex: 1,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
  },
  headerGradient: {
    paddingBottom: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.6)',
    marginTop: 2,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  headerRight: {
    width: 44,
    alignItems: 'flex-end',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
  },
  liveText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#ef4444',
    letterSpacing: 1,
  },
  // ELITE: Premium Header Styles - MyShake/ShakeAlert Inspired
  premiumHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  premiumBackButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  premiumHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  seismicTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  seismicIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.3)',
  },
  seismicTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  premiumLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.3)',
  },
  premiumLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22c55e',
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 4,
  },
  premiumLiveText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#22c55e',
    letterSpacing: 0.5,
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingBottom: 40,
  },
  visualizationContainer: {
    padding: 16,
  },
  visualizationCard: {
    height: 300,
    borderRadius: 20,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  glassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 20,
  },
  glowEffect: {
    position: 'absolute',
    width: '80%',
    height: '80%',
    borderRadius: 150,
    backgroundColor: 'rgba(249, 115, 22, 0.1)', // Orange glow
    opacity: 0.7,
    zIndex: -1,
  },
  locationContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  epicenterMarker: {
    position: 'absolute',
    left: '20%',
    top: '40%',
    alignItems: 'center',
  },
  epicenterDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#ef4444',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  epicenterLabel: {
    marginTop: 4,
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  userMarker: {
    position: 'absolute',
    right: '20%',
    top: '40%',
    alignItems: 'center',
  },
  userLabel: {
    marginTop: 4,
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  waveContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveCircle: {
    position: 'absolute',
    borderRadius: SCREEN_WIDTH * 0.4,
    borderWidth: 3,
  },
  pWaveCircle: {
    borderColor: '#3b82f6',
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  sWaveCircle: {
    borderColor: '#ef4444',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  distanceLine: {
    position: 'absolute',
    width: '60%',
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    top: '45%',
  },
  distanceLineInner: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
  },
  distanceText: {
    position: 'absolute',
    top: -20,
    left: '50%',
    transform: [{ translateX: -20 }],
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  // ELITE: Professional Radar Visualization Styles - USGS ShakeAlert Inspired
  radarGrid: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radarRing: {
    position: 'absolute',
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: 'rgba(100, 116, 139, 0.3)',
    backgroundColor: 'transparent',
  },
  radarCrosshairH: {
    position: 'absolute',
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(100, 116, 139, 0.2)',
  },
  radarCrosshairV: {
    position: 'absolute',
    width: 1,
    height: '100%',
    backgroundColor: 'rgba(100, 116, 139, 0.2)',
  },
  radarEpicenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  epicenterPulse: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderWidth: 2,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  epicenterCore: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#ef4444',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 8,
  },
  epicenterRadarLabel: {
    position: 'absolute',
    top: 28,
    fontSize: 9,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.7)',
    letterSpacing: 1,
  },
  pWaveFront: {
    position: 'absolute',
    borderRadius: 1000,
    borderWidth: 3,
    borderColor: '#3b82f6',
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
  sWaveFront: {
    position: 'absolute',
    borderRadius: 1000,
    borderWidth: 4,
    borderColor: '#ef4444',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 12,
    elevation: 6,
  },
  userRadarMarker: {
    position: 'absolute',
    alignItems: 'center',
    zIndex: 10,
  },
  userRadarDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22c55e',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 5,
  },
  userRadarLabel: {
    marginTop: 4,
    fontSize: 9,
    fontWeight: '700',
    color: '#22c55e',
    letterSpacing: 0.5,
  },
  distanceScale: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  distanceScaleText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
    letterSpacing: 0.3,
  },
  waveLegend: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    flexDirection: 'row',
    gap: 12,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  // ELITE: Premium 3-Axis Seismograph Card Styles
  seismographCard: {
    margin: 16,
    marginTop: 8,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  seismographGradient: {
    padding: 16,
  },
  seismographHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  seismographTitleRow: {
    flex: 1,
  },
  seismographTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 0.3,
  },
  seismographSubtitle: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.5)',
    marginTop: 2,
  },
  liveDataBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.3)',
  },
  liveDataDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22c55e',
    marginRight: 6,
  },
  liveDataText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#22c55e',
    letterSpacing: 0.5,
  },
  waveformContainer: {
    marginTop: 4,
  },
  amplitudeScale: {
    alignItems: 'flex-end',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  amplitudeText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.4)',
    fontFamily: 'monospace',
  },
  infoCard: {
    margin: 16,
    padding: 20,
    backgroundColor: ((colors as any).background?.secondary) || '#0f1419',
    borderRadius: 20,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  cardGlassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 20,
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  magnitudeBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#ef4444',
    borderRadius: 16,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  magnitudeText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  infoHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationText: {
    fontSize: 14,
    color: colors.text.secondary,
  },
  timesContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  timeCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  timeCardGlassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
  },
  timeIcon: {
    marginBottom: 8,
  },
  timeLabel: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 8,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeValue: {
    fontSize: 28,
    fontWeight: '900',
    color: '#fff',
    marginBottom: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  pWaveValue: {
    color: '#fff',
  },
  sWaveTime: {
    color: '#fff',
  },
  warningTime: {
    color: '#fff',
  },
  timeSubtext: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
    fontWeight: '500',
  },
  timeVelocity: {
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 4,
    fontWeight: '400',
  },
  intensityContainer: {
    marginBottom: 20,
  },
  intensityCard: {
    marginBottom: 12,
  },
  intensityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  intensityLabel: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  intensityValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginBottom: 8,
  },
  intensityValue: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text.primary,
  },
  intensityUncertainty: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  intensityBar: {
    height: 8,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
    borderRadius: 4,
    overflow: 'hidden',
  },
  intensityBarFill: {
    height: '100%',
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  intensityDescription: {
    marginTop: 8,
    fontSize: 11,
    color: colors.text.secondary,
    fontStyle: 'italic',
  },
  pgaCard: {
    padding: 16,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  pgaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  pgaLabel: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  pgaValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    marginBottom: 4,
  },
  pgaValue: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text.primary,
  },
  pgaUnit: {
    fontSize: 14,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  pgaUncertainty: {
    fontSize: 10,
    color: colors.text.secondary,
    marginTop: 4,
  },
  pgaDescription: {
    marginTop: 8,
    fontSize: 11,
    color: colors.text.secondary,
    fontStyle: 'italic',
  },
  qualityContainer: {
    marginTop: 20,
    gap: 12,
  },
  qualityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  qualityBadgeGlassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  qualityText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  qualityConfidence: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 11,
    fontWeight: '500',
  },
  methodContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  methodText: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: '500',
  },
  technicalDetailsContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    gap: 12,
  },
  technicalDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  technicalDetailLabel: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: '600',
    minWidth: 60,
  },
  technicalDetailValue: {
    fontSize: 12,
    color: colors.text.primary,
    fontWeight: '500',
    flex: 1,
  },
  listContainer: {
    margin: 16,
    marginTop: 0,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 12,
  },
  listItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: ((colors as any).background?.secondary) || '#0f1419',
    borderRadius: 12,
    marginBottom: 8,
  },
  listItemLeft: {
    flex: 1,
  },
  listItemMagnitude: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 4,
  },
  listItemLocation: {
    fontSize: 14,
    color: colors.text.secondary,
  },
  listItemRight: {
    alignItems: 'flex-end',
  },
  listItemWarningTime: {
    fontSize: 16,
    fontWeight: '700',
    color: '#f59e0b',
    marginBottom: 4,
  },
  listItemDistance: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  controlsContainer: {
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    paddingBottom: 32,
  },
  controlButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
    backgroundColor: ((colors as any).background?.secondary) || '#0f1419',
    borderRadius: 12,
  },
  controlButtonActive: {
    backgroundColor: ((colors as any).accent?.primary) || ((colors as any).primary?.main) || '#3b82f6',
  },
  controlButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  // CRITICAL: Real-time Monitoring Status Styles
  monitoringStatusContainer: {
    margin: 16,
    marginBottom: 8,
    gap: 8,
  },
  monitoringStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: ((colors as any).background?.secondary) || '#0f1419',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  monitoringStatusActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.5)',
  },
  monitoringStatusInactive: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
  },
  monitoringStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.text.secondary,
  },
  monitoringStatusDotActive: {
    backgroundColor: '#10b981',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 4,
  },
  monitoringStatusText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text.primary,
    flex: 1,
  },
  monitoringStatsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: ((colors as any).background?.primary) || '#0a0e1a',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  monitoringStatsText: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: '500',
    textAlign: 'center',
  },
  // CRITICAL: AI Analysis Card Styles - Life-saving Early Warning
  aiAnalysisContainer: {
    margin: 16,
    marginBottom: 8,
  },
  aiAnalysisCard: {
    borderRadius: 20,
    padding: 20,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
  },
  aiAnalysisGlassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
  },
  aiAnalysisHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  aiAnalysisTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aiAnalysisTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#fff',
  },
  riskScoreBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  riskScoreText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  aiAnalysisInfoContainer: {
    marginBottom: 16,
    padding: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  aiAnalysisInfoText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 18,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  aiPredictionContent: {
    gap: 16,
  },
  urgencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  urgencyText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  predictionDetails: {
    gap: 12,
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
  },
  predictionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  predictionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  predictionValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  recommendedActionContainer: {
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  recommendedActionText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    lineHeight: 22,
    textAlign: 'center',
  },
  factorBreakdown: {
    gap: 12,
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
  },
  factorBreakdownTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 8,
  },
  factorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  factorLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
    minWidth: 120,
  },
  factorBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  factorBar: {
    height: '100%',
    borderRadius: 4,
  },
  factorValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
    minWidth: 40,
    textAlign: 'right',
  },
  aiLoadingContainer: {
    padding: 32,
    alignItems: 'center',
    gap: 16,
  },
  aiLoadingText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  aiNoPredictionContainer: {
    padding: 32,
    alignItems: 'center',
    gap: 12,
  },
  aiNoPredictionText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
  },

  // ELITE: Real Map Styles
  mapContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 20,
    backgroundColor: '#0a0f1a',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
  },
  mapHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'rgba(10, 15, 26, 0.95)',
  },
  mapTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mapTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  mapInfoBadge: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  mapInfoText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ef4444',
  },
  mapWrapper: {
    height: SCREEN_WIDTH * 0.65,
    position: 'relative',
  },
  map: {
    flex: 1,
  },
  epicenterRing: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#ef4444',
    opacity: 0.6,
  },
  userMarkerDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#22c55e',
    borderWidth: 3,
    borderColor: '#ffffff',
  },
  userMarkerLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
    marginTop: 2,
    textShadowColor: '#000000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  mapLegendOverlay: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: 'rgba(10, 15, 26, 0.85)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    gap: 4,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  epicenterInfoOverlay: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(10, 15, 26, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  epicenterInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  epicenterInfoDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  epicenterInfoText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  epicenterInfoMag: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ef4444',
    marginTop: 2,
  },
});

export { styles, SCREEN_WIDTH, SCREEN_HEIGHT, colors };
