name: CI Rules-Aware Lint & Test

on:
  pull_request:

jobs:
  rules_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rules & Secrets Guard
        run: |
          echo "Running shell-based Rules & Secrets Guard..."
          # mandatory files
          for f in README.md LICENSE .gitignore; do
            if [ ! -f "$f" ]; then
              echo "::error::Mandatory file missing: $f"; exit 1; fi
          done
          # forbidden patterns
          if git grep -nE "console\\.log\(|debugPrint\(" -- \
            'src/**/*' \
            'app/**/*' \
            'App.tsx' \
            ':!src/utils/productionLogger.ts' \
            ':!**/*.test.*' \
            ':!**/__tests__/**' \
            ':!node_modules' ':!Pods' ':!ios/build' ':!android/build'; then
            echo "::error::Forbidden debug logging detected (console.log/debugPrint)."; exit 1;
          fi
          echo "✅ Rules & Secrets Guard passed"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Health Check
        run: npm ci || flutter pub get

      - name: Lint & Test
        run: |
          if [ -f "package.json" ]; then npm run lint && npm test; fi
          if [ -f "pubspec.yaml" ]; then flutter analyze && flutter test; fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: ./logs/

